sudo: false
dist: bionic
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libssl-dev
    - libunbound-dev
    - libidn2-0-dev 
    - libyaml-dev
    - check
    - libevent-dev
    - libev-dev
    - libuv-dev
    - valgrind
    - clang
    - wget
    - openssh-client
    - libgnutls28-dev
script:
  - mkdir tests
  - cd tests
# - ../src/test/tpkg/run-all.sh
  - ../src/test/tpkg/run-one.sh 225-stub-only-valgrind-checks.tpkg -V
